name: Node build
run-name: Build nodejs app
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm install

      # Ejecutar el linter para revisar la calidad del código.
      - name: Correr Lint
        working-directory: ./calculadora
        run: |
          npm run lint

      # Ejecutar las pruebas unitarias y de integración.
      - name: Correr Pruebas
        working-directory: ./calculadora
        run: |
          npm run test

      - name: Compilar
        working-directory: ./calculadora
        run: |
          npm run build